[meta]
name = "Dashboard"
author = "Miss"
category = "Overlay"

siteid = 103
version = "1.8.0"

blocks = [ "Plugin_Dashboard" ]

[script]
imports = [ "Icons.as" ]

exports = [ "Source/Export/Export.as" ]
shared_exports = [ "Source/Export/StateWrappers.as" ]

timeout = 0
