[meta]
name = "Dashboard"
author = "Miss"
category = "Overlay"
version = "1.8.1"

blocks = [ "Plugin_Dashboard" ]

[script]
exports = [ "Source/Export/Export.as" ]
shared_exports = [ "Source/Export/StateWrappers.as" ]

timeout = 0
